from __future__ import annotations

from app.dagster_etl import loaders
from app.dagster_etl.runtime import (
    EtlJobSpec,
    juso_monthly_identity,
    schedule_requires_any_env,
)

ALL_ETL_SPECS: tuple[EtlJobSpec, ...] = (
    EtlJobSpec(
        job_name="legal_dong_code_standard_quarterly",
        op_name="download_and_load_legal_dong_code_standard",
        dataset_key="legal_dong_code_standard",
        description="Download data.go.kr legal-dong code CSV and refresh TripMate code standard.",
        tags=("tripmate", "address", "legal-dong-code", "data-go"),
        loader=loaders.load_legal_dong_code_standard,
        success_message="법정동코드 기준 데이터 갱신 성공",
        failure_message="법정동코드 기준 데이터 갱신 실패",
    ),
    EtlJobSpec(
        job_name="juso_monthly_address_dataset",
        op_name="download_and_load_juso_monthly_address",
        dataset_key="juso_road_address_korean",
        description="Juso 도로명주소 한글 전체분과 관련 지번 TXT를 월 1회 갱신한다.",
        tags=("tripmate", "address", "juso"),
        loader=loaders.load_juso_monthly_address,
        success_message="Juso 월간 주소 데이터 갱신 성공",
        failure_message="Juso 월간 주소 데이터 갱신 실패",
        identity_resolver=juso_monthly_identity,
    ),
    EtlJobSpec(
        job_name="opinet_region_code_quarterly",
        op_name="load_opinet_region_codes",
        dataset_key="fuel_region_code",
        description=(
            "OpiNet areaCode.do 지역코드를 수집하고 Juso 법정동 기준 시도/시군구와 매핑한다."
        ),
        tags=("tripmate", "fuel", "opinet", "region-code"),
        loader=loaders.load_opinet_region_codes,
        success_message="OpiNet ETL 성공: {dataset_key}",
        failure_message="OpiNet ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="opinet_avg_price_daily",
        op_name="load_opinet_avg_prices",
        dataset_key="fuel_avg_price",
        description="OpiNet avgAllPrice.do 전국 일별 평균 유가를 수집한다.",
        tags=("tripmate", "fuel", "opinet", "average-price"),
        loader=loaders.load_opinet_avg_prices,
        success_message="OpiNet ETL 성공: {dataset_key}",
        failure_message="OpiNet ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="opinet_lowest_station_daily",
        op_name="load_opinet_lowest_stations_for_all_sigungu",
        dataset_key="fuel_lowest_station",
        description="OpiNet lowTop10.do 최저가 주유소 후보를 전국 시군구 기준으로 수집한다.",
        tags=("tripmate", "fuel", "opinet", "lowest-station"),
        loader=loaders.load_opinet_lowest_stations,
        success_message="OpiNet ETL 성공: {dataset_key}",
        failure_message="OpiNet ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="rest_area_master_monthly",
        op_name="load_rest_area_master",
        dataset_key="rest_area_master",
        description="한국도로공사 휴게소 기본정보를 월 1회 수집한다.",
        tags=("tripmate", "rest-area", "expressway", "master"),
        loader=loaders.load_rest_area_master_dataset,
        success_message="한국도로공사 휴게소 ETL 성공: {dataset_key}",
        failure_message="한국도로공사 휴게소 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="rest_area_oil_price_daily",
        op_name="load_rest_area_oil_prices",
        dataset_key="rest_area_oil_price",
        description="한국도로공사 휴게소 주유소 가격/업체 현황을 하루 2회 수집한다.",
        tags=("tripmate", "rest-area", "expressway", "oil-price"),
        loader=loaders.load_rest_area_oil_prices_dataset,
        success_message="한국도로공사 휴게소 ETL 성공: {dataset_key}",
        failure_message="한국도로공사 휴게소 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="rest_area_service_monthly",
        op_name="load_rest_area_services",
        dataset_key="rest_area_svcs",
        description="한국도로공사 휴게소 편의시설 현황을 월 1회 수집한다.",
        tags=("tripmate", "rest-area", "expressway", "service"),
        loader=loaders.load_rest_area_services_dataset,
        success_message="한국도로공사 휴게소 ETL 성공: {dataset_key}",
        failure_message="한국도로공사 휴게소 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="weather_short_term_sigungu_grid",
        op_name="load_weather_short_term",
        dataset_key="weather_short_term",
        description="기상청 초단기실황을 활성화된 시군구 대표 격자 단위로 수집한다.",
        tags=("tripmate", "weather", "kma", "short-term"),
        loader=loaders.load_weather_short_term,
        success_message="날씨/대기질 ETL 성공: {dataset_key}",
        failure_message="날씨/대기질 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="weather_kma_alert",
        op_name="load_weather_kma_alerts",
        dataset_key="weather_kma_alert",
        description="기상청 기상특보, 기상정보, 기상속보 목록을 텔레그램 알림용으로 수집한다.",
        tags=("tripmate", "weather", "kma", "alert"),
        loader=loaders.load_weather_alerts,
        success_message="날씨/대기질 ETL 성공: {dataset_key}",
        failure_message="날씨/대기질 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="weather_mid_term_nationwide",
        op_name="load_weather_mid_term",
        dataset_key="weather_mid_term",
        description="기상청 중기예보 공식 구역코드 전체를 주기 수집한다.",
        tags=("tripmate", "weather", "kma", "mid-term"),
        loader=loaders.load_weather_mid_term,
        success_message="날씨/대기질 ETL 성공: {dataset_key}",
        failure_message="날씨/대기질 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="air_quality_station_daily",
        op_name="load_air_quality_stations",
        dataset_key="air_quality_station",
        description="에어코리아 측정소 목록을 수집하고 법정동 경계와 매핑한다.",
        tags=("tripmate", "air-quality", "airkorea", "station"),
        loader=loaders.load_air_quality_stations_dataset,
        success_message="날씨/대기질 ETL 성공: {dataset_key}",
        failure_message="날씨/대기질 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="air_quality_forecast_daily",
        op_name="load_air_quality_forecasts",
        dataset_key="air_quality_forecast",
        description="에어코리아 미세먼지/오존 예보통보를 수집한다.",
        tags=("tripmate", "air-quality", "airkorea", "forecast"),
        loader=loaders.load_air_quality_forecasts_dataset,
        success_message="날씨/대기질 ETL 성공: {dataset_key}",
        failure_message="날씨/대기질 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="air_quality_sido_measurement_hourly",
        op_name="load_air_quality_sido_measurements",
        dataset_key="air_quality_sido_measurement",
        description="에어코리아 시도별 실시간 측정값을 시간 단위로 수집한다.",
        tags=("tripmate", "air-quality", "airkorea", "measurement"),
        loader=loaders.load_air_quality_measurements_dataset,
        success_message="날씨/대기질 ETL 성공: {dataset_key}",
        failure_message="날씨/대기질 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="kma_recommended_tour_course_annual",
        op_name="load_kma_recommended_tour_course",
        dataset_key="kma_recommended_tour_course",
        description="기상청 추천 관광코스 CSV/ZIP 파일을 DB화한다.",
        tags=("tripmate", "tour", "kma", "course"),
        loader=loaders.load_kma_tour_course_dataset,
        success_message="날씨/대기질 ETL 성공: {dataset_key}",
        failure_message="날씨/대기질 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="kma_beach_catalog_annual",
        op_name="load_kma_beach_catalog",
        dataset_key="kma_beach_catalog",
        description="기상청 전국 해수욕장 위치 카탈로그를 장소 DB와 매핑한다.",
        tags=("tripmate", "weather", "kma", "beach", "catalog"),
        loader=loaders.load_kma_beach_catalog_dataset,
        success_message="해수욕장 날씨 ETL 성공: {dataset_key}",
        failure_message="해수욕장 날씨 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="kma_beach_ultra_short_forecast_hourly",
        op_name="load_kma_beach_ultra_short_forecasts",
        dataset_key="kma_beach_ultra_short_forecast",
        description="해수욕장별 기상청 초단기예보를 6~8월 시간 단위로 수집한다.",
        tags=("tripmate", "weather", "kma", "beach", "ultra-short"),
        loader=loaders.load_kma_beach_ultra_short,
        success_message="해수욕장 날씨 ETL 성공: {dataset_key}",
        failure_message="해수욕장 날씨 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="kma_beach_village_forecast_3hourly",
        op_name="load_kma_beach_village_forecasts",
        dataset_key="kma_beach_village_forecast",
        description="해수욕장별 기상청 단기예보를 6~8월 3시간 기준으로 수집한다.",
        tags=("tripmate", "weather", "kma", "beach", "village"),
        loader=loaders.load_kma_beach_village,
        success_message="해수욕장 날씨 ETL 성공: {dataset_key}",
        failure_message="해수욕장 날씨 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="kma_beach_wave_height_hourly",
        op_name="load_kma_beach_wave_heights",
        dataset_key="kma_beach_wave_height",
        description="해수욕장별 파고 관측값을 6~8월 시간 단위로 수집한다.",
        tags=("tripmate", "weather", "kma", "beach", "wave"),
        loader=loaders.load_kma_beach_wave,
        success_message="해수욕장 날씨 ETL 성공: {dataset_key}",
        failure_message="해수욕장 날씨 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="kma_beach_water_temperature_hourly",
        op_name="load_kma_beach_water_temperatures",
        dataset_key="kma_beach_water_temperature",
        description="해수욕장별 수온 관측값을 6~8월 시간 단위로 수집한다.",
        tags=("tripmate", "weather", "kma", "beach", "water-temperature"),
        loader=loaders.load_kma_beach_water_temperature,
        success_message="해수욕장 날씨 ETL 성공: {dataset_key}",
        failure_message="해수욕장 날씨 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="kma_beach_tide_sun_daily",
        op_name="load_kma_beach_tide_sun",
        dataset_key="kma_beach_tide_sun",
        description="해수욕장별 조석과 일출·일몰 정보를 6~8월 일 단위로 수집한다.",
        tags=("tripmate", "weather", "kma", "beach", "tide", "sun"),
        loader=loaders.load_kma_beach_tide_sun,
        success_message="해수욕장 날씨 ETL 성공: {dataset_key}",
        failure_message="해수욕장 날씨 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="khoa_beach_observation_hourly",
        op_name="load_khoa_beach_observations",
        dataset_key="khoa_beach_observation",
        description="KHOA 해수욕장 최신 수온·파고·풍향풍속 관측값을 시간 단위로 수집한다.",
        tags=("tripmate", "beach", "khoa", "observation"),
        loader=loaders.load_khoa_beach_observations_dataset,
        success_message="해수욕장 통합 ETL 성공: {dataset_key}",
        failure_message="해수욕장 통합 ETL 실패: {dataset_key}",
        schedule_enabled=schedule_requires_any_env("TRIPMATE_KHOA_API_KEY"),
    ),
    EtlJobSpec(
        job_name="khoa_beach_index_forecast_twice_daily",
        op_name="load_khoa_beach_index_forecasts",
        dataset_key="khoa_beach_index_forecast",
        description="KHOA 해수욕지수 예측 정보를 원천 갱신주기에 맞춰 하루 2회 수집한다.",
        tags=("tripmate", "beach", "khoa", "index"),
        loader=loaders.load_khoa_beach_index_forecasts_dataset,
        success_message="해수욕장 통합 ETL 성공: {dataset_key}",
        failure_message="해수욕장 통합 ETL 실패: {dataset_key}",
        schedule_enabled=schedule_requires_any_env(
            "TRIPMATE_KHOA_API_KEY",
            "TRIPMATE_DATA_GO_SERVICE_KEY",
        ),
    ),
    EtlJobSpec(
        job_name="mof_beach_info_annual",
        op_name="load_mof_beach_info",
        dataset_key="mof_beach_info",
        description="해양수산부 해수욕장 기본정보를 원천 첨부문서 기준 연 1회 수집한다.",
        tags=("tripmate", "beach", "data-go-kr", "mof"),
        loader=loaders.load_mof_beach_info_dataset,
        success_message="해수욕장 통합 ETL 성공: {dataset_key}",
        failure_message="해수욕장 통합 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="mof_beach_water_quality_annual",
        op_name="load_mof_beach_water_quality",
        dataset_key="mof_beach_water_quality",
        description="해양수산부 해수욕장 수질적합 여부를 원천 첨부문서 기준 연 1회 수집한다.",
        tags=("tripmate", "beach", "data-go-kr", "mof", "water-quality"),
        loader=loaders.load_mof_beach_water_quality_dataset,
        success_message="해수욕장 통합 ETL 성공: {dataset_key}",
        failure_message="해수욕장 통합 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="khoa_mudflat_index_forecast_twice_daily",
        op_name="load_khoa_mudflat_index_forecasts",
        dataset_key="khoa_mudflat_index_forecast",
        description="KHOA 갯벌체험지수 예측 정보를 하루 2회 수집한다.",
        tags=("tripmate", "ocean", "khoa", "mudflat"),
        loader=loaders.load_khoa_ocean_index_dataset_by_key,
        success_message="KHOA 해양지수 ETL 성공: {dataset_key}",
        failure_message="KHOA 해양지수 ETL 실패: {dataset_key}",
        schedule_enabled=schedule_requires_any_env(
            "TRIPMATE_KHOA_API_KEY",
            "TRIPMATE_DATA_GO_SERVICE_KEY",
        ),
    ),
    EtlJobSpec(
        job_name="khoa_sea_split_index_forecast_twice_daily",
        op_name="load_khoa_sea_split_index_forecasts",
        dataset_key="khoa_sea_split_index_forecast",
        description="KHOA 바다갈라짐 체험지수 예측 정보를 하루 2회 수집한다.",
        tags=("tripmate", "ocean", "khoa", "sea-split"),
        loader=loaders.load_khoa_ocean_index_dataset_by_key,
        success_message="KHOA 해양지수 ETL 성공: {dataset_key}",
        failure_message="KHOA 해양지수 ETL 실패: {dataset_key}",
        schedule_enabled=schedule_requires_any_env(
            "TRIPMATE_KHOA_API_KEY",
            "TRIPMATE_DATA_GO_SERVICE_KEY",
        ),
    ),
    EtlJobSpec(
        job_name="public_cultural_festival_quarterly",
        op_name="load_public_cultural_festivals",
        dataset_key="public_cultural_festival",
        description="전국문화축제표준데이터를 분기 수집해 축제 raw/serving DB에 반영한다.",
        tags=("tripmate", "festival", "data-go-kr"),
        loader=loaders.load_public_cultural_festival_dataset,
        success_message="전국문화축제표준데이터 ETL 성공: {dataset_key}",
        failure_message="전국문화축제표준데이터 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="public_arboretum_basic_annual",
        op_name="load_public_arboretum_basic",
        dataset_key="public_arboretum_basic",
        description="한국수목원정원관리원 수목원 기본관람정보를 저빈도 확인 수집한다.",
        tags=("tripmate", "place", "data-go-kr", "arboretum"),
        loader=loaders.load_public_place_dataset_by_key,
        success_message="공공 장소 ETL 성공: {dataset_key}",
        failure_message="공공 장소 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="public_tourist_information_center_annual",
        op_name="load_public_tourist_information_center",
        dataset_key="public_tourist_information_center",
        description="전국관광안내소표준데이터를 연간 수집해 표준 장소 DB에 반영한다.",
        tags=("tripmate", "place", "data-go-kr", "tourist-information"),
        loader=loaders.load_public_place_dataset_by_key,
        success_message="공공 장소 ETL 성공: {dataset_key}",
        failure_message="공공 장소 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="public_recreation_forest_semiannual",
        op_name="load_public_recreation_forest",
        dataset_key="public_recreation_forest",
        description="전국휴양림표준데이터를 반기 수집해 표준 장소 DB에 반영한다.",
        tags=("tripmate", "place", "data-go-kr", "forest"),
        loader=loaders.load_public_place_dataset_by_key,
        success_message="공공 장소 ETL 성공: {dataset_key}",
        failure_message="공공 장소 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="public_museum_art_gallery_annual",
        op_name="load_public_museum_art_gallery",
        dataset_key="public_museum_art_gallery",
        description="전국박물관미술관정보표준데이터를 연간 수집해 표준 장소 DB에 반영한다.",
        tags=("tripmate", "place", "data-go-kr", "museum", "art"),
        loader=loaders.load_public_place_dataset_by_key,
        success_message="공공 장소 ETL 성공: {dataset_key}",
        failure_message="공공 장소 ETL 실패: {dataset_key}",
    ),
    EtlJobSpec(
        job_name="public_campground_daily",
        op_name="load_public_campground",
        dataset_key="public_campground",
        description="전국야영(캠핑)장표준데이터를 매일 수집해 표준 장소 DB에 반영한다.",
        tags=("tripmate", "place", "data-go-kr", "campground"),
        loader=loaders.load_public_place_dataset_by_key,
        success_message="공공 장소 ETL 성공: {dataset_key}",
        failure_message="공공 장소 ETL 실패: {dataset_key}",
    ),
)
